export default {
  lowongan: [
    {
      id: 0,
      image: "assets/images/image8.jpg",
      namaPerusahaan: "PT Web Media Technology Indonesia",
      lowongan: "Technical Chat Support",
      tags: "IT Support",
      lokasi: "bali",
      kriteria: [
        "Exceptional English Skills (C1 or higher).",
        "Minimum Diploma in any field (IT field is a plus)",
        "Interest in IT and having knowledge in the domain, hosting, blog, and website will be  valued",
        "You enjoy communicating and helping people",
        "You are friendly and motivated to conquer the internet",
      ],
      email: "karir@niagahoster.co.id",
      date: "1/2/2021",
    },
    {
      id: 2,
      image: "assets/images/image8.jpg",
      namaPerusahaan: "PT Web Media Technology Indonesia",
      lowongan: "System Administrator",
      tags: "Admin System",
      lokasi: "Klaten",
      kriteria: [
        "Bachelor degree in technology-related fields or equivalent. ",
        "A solid understanding of Linux system administration.",
        "A solid understanding of networking, firewalls, load balancers, TCP/IP, security  standards. ",
        "Solid networking knowledge (OSI network layers, TCP/IP)",
        "Good to have Experienced with Ansible, Chef, IPMI / iDrac, RAID, FSCK,  VMWARE, OVZ 7, Vanguard",
      ],
      email: "karir@niagahoster.co.id",
      date: "10/2/2021",
    },
    {
      id: 3,
      image: "assets/images/image10.jpg",
      namaPerusahaan: "PT Erlimpex",
      lowongan: "Android Programmer ",
      tags: "Programmer",
      lokasi: "Semarang",
      kriteria: [
        "Menguasai Android Studio, Java, JSON, PHP",
        "Menguasai HTML, CSS, Javascript, Jquery",
        "Menguasai teknik pemrograman dan database dengan baik. ",
        "Mampu membaca spesifikasi pekerjaan dan mengimplementasikannya dalam kode  program. ",
        "Mampu berkomunikasi dengan baik",
        "Terbiasa dengan deadline.",
        " Jujur, bertanggung jawab, mau belajar dan berkembang.",
        " Dapat bekerja dalam team maupun individu. ",
        " Pernah mengerjakan project mobile/android programming (portfolio diutamakan).",
      ],
      email: "lowongan@erlimplex.co.id",
      date: "30/1/2021",
    },
    {
      id: 3,
      image: "assets/images/image10.jpg",
      namaPerusahaan: "PT Erlimpex",
      lowongan: "Android Programmer ",
      tags: "Programmer",
      lokasi: "Semarang",
      kriteria: [
        "Menguasai Android Studio, Java, JSON, PHP",
        "Menguasai HTML, CSS, Javascript, Jquery",
        "Menguasai teknik pemrograman dan database dengan baik. ",
        "Mampu membaca spesifikasi pekerjaan dan mengimplementasikannya dalam kode  program. ",
        "Mampu berkomunikasi dengan baik",
        "Terbiasa dengan deadline.",
        " Jujur, bertanggung jawab, mau belajar dan berkembang.",
        " Dapat bekerja dalam team maupun individu. ",
        " Pernah mengerjakan project mobile/android programming (portfolio diutamakan).",
      ],
      email: "lowongan@erlimplex.co.id",
      date: "30/1/2021",
    },
  ], // end lowongan data
};
