export default {
  lowongan: [
    {
      id: 0,
      imageId: 8,
      namaPerusahaan: "PT Web Media Technology Indonesia",
      namaLowongan: "Technical Chat Support",
      tags: "IT Support",
      lokasi: "bali",
      kriteria: [
        "Exceptional English Skills (C1 or higher).",
        "Minimum Diploma in any field (IT field is a plus)",
        "Interest in IT and having knowledge in the domain, hosting, blog, and website will be  valued",
        "You enjoy communicating and helping people",
        "You are friendly and motivated to conquer the internet",
      ],
      email: "karir@niagahoster.co.id",
      date: "1/2/2021",
    },
    {
      id: 1,
      imageId: 8,
      namaPerusahaan: "PT Web Media Technology Indonesia",
      namaLowongan: "System Administrator",
      tags: "Admin System",
      lokasi: "Klaten",
      kriteria: [
        "Bachelor degree in technology-related fields or equivalent.",
        "A solid understanding of Linux system administration.",
        "A solid understanding of networking, firewalls, load balancers, TCP/IP, security  standards. ",
        "Solid networking knowledge (OSI network layers, TCP/IP)",
        "Good to have Experienced with Ansible, Chef, IPMI / iDrac, RAID, FSCK,  VMWARE, OVZ 7, Vanguard",
      ],
      email: "karir@niagahoster.co.id",
      date: "10/2/2021",
    },
    {
      id: 2,
      imageId: 10,
      namaPerusahaan: "PT Erlimpex",
      namaLowongan: "Android Programmer ",
      tags: "Programmer",
      lokasi: "Semarang",
      kriteria: [
        "Menguasai Android Studio, Java, JSON, PHP",
        "Menguasai HTML, CSS, Javascript, Jquery",
        "Menguasai teknik pemrograman dan database dengan baik. ",
        "Mampu membaca spesifikasi pekerjaan dan mengimplementasikannya dalam kode  program. ",
        "Mampu berkomunikasi dengan baik",
        "Terbiasa dengan deadline.",
        " Jujur, bertanggung jawab, mau belajar dan berkembang.",
        " Dapat bekerja dalam team maupun individu. ",
        " Pernah mengerjakan project mobile/android programming (portfolio diutamakan).",
      ],
      email: "lowongan@erlimplex.co.id",
      date: "30/1/2021",
    },
    {
      id: 3,
      imageId: 9,
      namaPerusahaan: "PT Berca Hardayaperkasa ",
      namaLowongan: " IT Support",
      tags: " IT Support",
      lokasi: "Jakarta",
      kriteria: [
        "At least 1 year of working experience in related field",
        "Hardware knowledge : Desktop PC dan Notebook. ",
        "Operating System and Application knowledge : Windows.",
        "Basic knowledge in Network (LAN, WAN, VPN), DNS, TCP/IP, and Firewall  Technologies.",
        "Mampu berkomunikasi dengan baik",
        "Willing to work SHIFT if needed. ",

        "Willing to travel whenever required.",
      ],
      email: "career@bercahardayaperkasa.co.id",
      date: "31/1/2021",
    },
    {
      id: 4,
      imageId: 5,
      namaPerusahaan: "PT Bumi Teknik Utama ",
      namaLowongan: "Manager ICT",
      tags: "Manage",
      lokasi: "Jakarta pusat",
      kriteria: [
        "Usia maksimal 35 tahun ",
        "Minimal S1 Teknik informatika/Sistem Informatika ",
        "Pengalaman 3 - 4 Tahun dibidang yang sama ",
        "Mampu berbahasa Inggris ",
        "Mengerti dan Memahami Management ICT ",
        "Mengerti dan Memahami Infrasktur ICT ( Networking, Server, Virtualisasi,  Telekomunikasi, Security, ICT Device, dan lain – lain ) ",
        "Mengerti Infra structure di LAN, WAN dengan Mananged Switch ",
        "Mengerti Sophos, Citrix ",
        "Memahami Trouble Shooting PC and Server ",
        "Memahami VOIP dan CCTV ",
        "Backup data di Acronis dan Synology ",
        "Memiliki Analisa dan logika yang baik.Teliti dan memiliki motivasi kerja yang tinggi ",
        "Memiliki kemauan keras dalam mempelajari teknologi software terbaru ",
        "Dapat bekerja secara Tim dan mau belajar ",
        "Mampu mengelola dan mengembangkan Tim IT ",
        "Penempatan Jakarta Pusat ",
      ],
      email: "lowongan@bumiteknikutama.com",
      date: "31/4/2021",
    },
    {
      id: 5,
      imageId: 4,
      namaPerusahaan: "PT Puninar Jaya",
      namaLowongan: "Web Front End Programmer",
      tags: "Front end",
      lokasi: "Jakarta Timur",
      kriteria: [
        "Having strong abilities in PHP, Laravel framework ",
        "Get to know Web UI/UX Design ",
        "Experience with HTML5, Bootstrap, CSS3, Javascript, and JQuery ",
        "Experience using PostgreeSQL, Oracle databases ",
        "Experience using Rest API, Soap API, GIT ",
        "Experience in system integration for web development ",
        "Experience minimum 2 years ",
        "Minimum education bachelor degree of IT ",
        "Experience working in the Agile / Scrum environment ",
        "Experience working in multiple projects ",
      ],
      email: "career@puniar.co.id",
      date: "31/3/2021",
    },
    {
      id: 6,
      imageId: 7,
      namaPerusahaan: "PT Multi Wahana Kencana",
      namaLowongan: "IT Staff",
      tags: "Manage",
      lokasi: "Bandung",
      kriteria: [
        "S1 Teknik Informatika / Teknik Komputer ",
        "Menguasai Pemrograman Website (HTML, PHP, MySQL, CSS, JavaScript),  memahami framework Laravel / CodeIgniter menjadi nilai lebih. ",
        "Menguasai Android Studio ",
        "Pernah membuat Website dan Aplikasi Android ",
        "Menguasai Troubleshooting Komputer dan Jaringan ",
        "Mengetahui konsep jaringan ",
      ],
      email: "job@multikencana.co.id",
      date: "9/2/2021",
    },
    {
      id: 7,
      imageId: 6,
      namaPerusahaan: "PT Inkor Sinergi Mandiri",
      namaLowongan: "Presales Consultant",
      tags: "Marketing",
      lokasi: "Jakarta Utara",
      kriteria: [
        "Candidate must possess at least Bachelor's Degree in Engineering (Computer/Telecommunication), Engineering (Electrical/Electronic) or equivalent. ",
        "Required language(s): English",
        "At least 5 Year(s) of working experience in the related field is required for this  position. ",
        "Required Skill(s): Presentation, Negotiation, Communication, Problem Solving, Time  Management, Leadership ",
        "Preferably Supervisor/Coordinator specialized in IT/Computer ",
        "Network/System/Database Admin or equivalent.",
      ],
      email: "career@inkorsinergi.co.id",
      date: "1/2/2021",
    },
    {
      id: 8,
      imageId: 2,
      namaPerusahaan: "PT Sisindokom Lintasbuana",
      namaLowongan: "Network Engineer (CCNP)",
      tags: "Network",
      lokasi: "Jakarta Pusat",
      kriteria: [
        "Experience at least 3 years ",
        "Candidate must possess at least a bachelor's degree, computer science/information  technology, engineering (computer/telecommunication) or equivalent ",
        "Having CCNP Certification (is a must) ",
        "Understands router & networking ",
        "Highly self motivated w/ confident ",
        "Flexible hours and travel within the serving ",
        "Work independently or part of a team ",
        "Good communication and good attitude. ",
      ],
      email: "career@sisdokom.co.id",
      date: "19/2/2021",
    },
    {
      id: 9,
      imageId: 1,
      namaPerusahaan: "PT Home Center Indonesia (Informa Furnishigs)",
      namaLowongan: "DATA ARCHITECT",
      tags: "Data engineer",
      lokasi: "Jakarta Barat",
      kriteria: [
        "Must be a strategic thinker with strong influencing skills. ",
        "Demonstrated effective oral and written communication skills including both the  ability to address detailed technical communications as well as the ability to  distill complete technical status to executive level. ",
        "Excellent interpersonal skills. ",
        "Strong analytical skills with an ability to recommend changes. ",
        "Must possess a high sense of urgency and work ethic. ",
        "Must be a self-starter who can work with minimal supervision, with the  expectation of working as a motivated and cooperative team member. ",
        "Must be detail oriented, reliable, financially responsible, and have a proven track  record of accomplishments.",
        "Demonstrated ability to develop sizing & capacity planning for large scale big  data platforms and to periodically evaluate and optimize performance and  platform throughput. ",
        "Expertise and experience with software development and related techniques and  methodologies such Agile. ",
        "Experience with development of analytics and data science-based solutions using  open source tools and libraries is required. ",
        "Experience in building full pipeline including distributed Machine Learning  models (e.g., training/test pipeline, offer eligibility, data layer, feature layer, etc.) ",
        "Proficient in Big Data Technologies (EMR, Hadoop, Hive, etc) ",
        "Proficient in PySpark, Python, SQL, Java/Scala, No SQL ",
        "Expertise and experience with software development and related techniques and  methodologies such Agile. ",
        "Experience with development of analytics and data science based solutions using  open source tools and libraries is required",
        "Knowledge of AWS Cloud technologies is preferred ",
        "Familiarity with building data pipelines, data modeling, architecture &  governance concepts ",
        "Experience implementing ML models and building highly scalable and high  availability systems ",
        "Experience building, launching and maintaining complex analytics pipelines in  production ",
        "Strong development experience with Python, Java, Scala, and related Linux based scripting tools ",
      ],
      email: "career@informa.co.id",
      date: "7/2/2021",
    },
    {
      id: 10,
      imageId: 3,
      namaPerusahaan: "PT Indo Pratama Teleglobal",
      namaLowongan: "HUB Enginee",
      tags: "Network",
      lokasi: "Jakarta Timur",
      kriteria: [
        "Memiliki pengalaman sebagai Hub Engineer selama 3 tahun.",
        "Pendidikan minimal Sarjana Teknik Informatika dengan usia maksimal 35 tahun.",
        "Memiliki etos kerja yang tinggi dan loyal terhadap perusahaan.",
        "Mahir tentang VSAT Network, TCP/IP & Routers.",
      ],
      email: "job@indopratama.com",
      date: "24/2/2021",
    },
  ], // end lowongan data
};
